# Generated by Django 5.0.7 on 2024-08-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_user_options_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
